services:
  mongo:
    image: mongo
    container_name: mongo_yelp
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  postgres:
    image: postgres:15
    container_name: postgres_yelp
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: always
volumes:
  pgdata:
