version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_yelp
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
